[project]
name = "yt-down"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moviepy>=2.2.1",
    "python-dotenv>=1.1.1",
    "pytube>=15.0.0",
    "ruff>=0.14.0",
]
